---
title: "Plotting Average MFLOPS vs. Log2 N"
author: "Rami Pellumbi"
date: "September 17, 2023"
output:
  pdf_document: default
---

```{r}
library(pubtheme)
library(tidyverse)
```

```{r}
data <- read_csv("a1/part2/data/part_2_data.csv", show_col_types = FALSE)
```

```{r}
summarized_data <- data %>%
  mutate(N = log2(N)) %>%
  group_by(N) %>%
  summarize(avg_mflops = mean(MFLOPS), sd_mflops = sd(MFLOPS))
```

```{r}
plot <- summarized_data %>%
  ggplot(aes(x = N, y = avg_mflops)) +
  geom_point(aes(color = "Average Observation")) +
  geom_errorbar(
    aes(ymin = avg_mflops - sd_mflops,
        ymax = avg_mflops + sd_mflops,
        color = "Standard Deviation"),
    width = 0.1
  ) +
  scale_color_manual(
    values = c("Average Observation" = "blue", "Standard Deviation" = "red")
  ) +
  labs(
    x = "Log2 N",
    y = "MFLOPS",
    title = "Average MFLOPS vs. Log2 N",
    color = "Legend"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.title.x = element_text(face = "bold"),
    axis.title.y = element_text(face = "bold")
  ) +
  theme_pub(type = "scatter")

ggsave("a1/part2/data/part_2_plot.pdf", plot, width = 6, height = 8, dpi = 600)
```